### ISSUE TITLE
Additional Questions on Assessments

### ISSUE THREAD

**Issue by JeffreyBytes** [elmoallistair/Google-IT-Support#9]
The assessment questions are picked randomly from a pool of questions. Should I add additional questions to the graded assessments as I find them or just keep correcting the ones that are incorrect on here?

Thanks! I'm not familiar with the scope of this repo, and don't want to overstep. :)

**Comment by elmoallistair** [comment]
Hi Jeffrey, actually this repository was created to **document** my progress. regarding the additional questions you have mentioned, of course, they provide multiple questions per topic and can differ from mine, what I wrote here are **the questions I got in my own quiz**. I'd like to add all the questions but I think it will be complicated and take a long time.

Also, you can contribute by correcting the wrong answers :)

Thanks~
